#+title: Token Maker

* About
Goal of this project is to create a fully functional, fast and easy to use program for making tokens, cards, figurines and similar art for use in tabletop roleplaying games and similar environments.

The program is already advanced enough to be suitable for use. There are many more features I want to implement before I'm satisfied enough to call it complete tho.

I've made a video showcasing the program and it's features. You can view it here: [[https://www.youtube.com/watch?v=m3oKcxm5JHw][Link]]

The project is currently not in active development.

* Manual
The program should be self explanatory for the most part but if you need detailed explanations of its functionality, you can read the [[./MANUAL.org][Manual]] document.

* Contributing
If you find any bugs or issues with the program, please notify me by writing an issue describing the problem and steps to reproduce it.

The easiest way to contribute to the project would be to donate to the development fund. You can do so here: [[https://www.buymeacoffee.com/purrie][Link]]

Before making feature suggestions, please familiarize yourself with the roadmap of the project. If the feature you want isn't planned yet, you can describe the functionality you wish to be added by writing an issue.

If you wish to contribute art or code to the project, familiarize yourself with the roadmap and write an issue describing what you wish to contribute before you start working as to avoid duplicate work and help coordinate the efforts.

Please keep in mind that I'm only accepting contributions of art and code that you made yourself or have rights to. Any contributions must follow the same licensing scheme as described in the copyright document.

* Building
To build the project you need Cargo to handle rust dependencies. Some dependencies of the program require that you have cmake, openssl v1 or later and fontconfig development libraries installed on your system.

You can use Just command runner to execute build and installation scripts.

Most common operations you will want to use is installation or removal. Those can be achieved with following commands:
#+BEGIN_SRC shell
just install
#+END_SRC

#+BEGIN_SRC shell
just remove
#+END_SRC
Keep in mind that current removal script removes all files related to the program, which means if you created your own custom frames, those will be deleted too!

* License
Token Maker
Copyright (C) 2023 Purrie Brightstar

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 2 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

The art of the program is licensed under CC-BY-SA / CC-BY licenses as described in the copyright document.
